kind: ConfigMap
apiVersion: v1
metadata:
  name: ecommerce-configmap
  namespace: mernstack

data:
  MONGO_ROOT_USERNAME: merndb # plain text , no need to base64 encode
  MONGO_ROOT_DB: mernapp
  PORT: "5000"